branches:
    - dev

prepare:
    - path: "@semantic-release/exec"
      cmd: "vsce package --out vite-serve-${nextRelease.version}.vsix"

npmPublish: false

assets:
  - "vite-serve-*.vsix"

success:
    # - path: "@semantic-release/exec"
    #   cmd: "vsce publish --pat $VSCE_TOKEN"

    - path: "@semantic-release/exec"
      cmd: "git push && git push --tags"
