name: Release & Publish to VSCode Marketplace

on:
    push:
        branches:
            - main

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install dependencies
              run: npm ci

            - name: Run semantic-release
              env:
                  GH_TOKEN: ${{ secrets.GH_AUTH_TOKEN }}
                  GIT_AUTHOR_NAME: phondani0
                  GIT_AUTHOR_EMAIL: ankitphondani52@gmail.com
                  GIT_COMMITTER_NAME: phondani0
                  GIT_COMMITTER_EMAIL: ankitphondani52@gmail.com
                  VSCE_TOKEN: ${{ secrets.VSCODE_PUBLISHER_TOKEN }}
              run: npx semantic-release
